"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";

/* ─── NAV ──────────────────────────────────────────────────────── */
function Nav() {
  return (
    <nav
      style={{
        position: "fixed",
        top: 0,
        left: 0,
        right: 0,
        zIndex: 100,
        padding: "0 40px",
        height: 64,
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        borderBottom: "1px solid var(--border)",
        background: "rgba(10,15,30,0.85)",
        backdropFilter: "blur(12px)",
      }}
    >
      <span
        style={{
          fontFamily: "'Space Grotesk', sans-serif",
          fontSize: 20,
          fontWeight: 700,
          letterSpacing: "-0.5px",
          color: "var(--white)",
        }}
      >
        Pulse<span style={{ color: "var(--cyan)" }}>.</span>
      </span>
      <div style={{ display: "flex", gap: 32, alignItems: "center" }}>
        <a href="#features" style={{ color: "var(--muted)", fontSize: 14, fontWeight: 500 }}>Features</a>
        <a href="#integrations" style={{ color: "var(--muted)", fontSize: 14, fontWeight: 500 }}>Integrations</a>
        <a href="#pricing" style={{ color: "var(--muted)", fontSize: 14, fontWeight: 500 }}>Pricing</a>
        <Link href="/sign-in" style={{ color: "var(--muted)", fontSize: 14, fontWeight: 500 }}>Log in</Link>
        <a
          href="#pricing"
          style={{
            background: "var(--cyan)",
            color: "var(--navy)",
            padding: "9px 20px",
            borderRadius: 8,
            fontSize: 14,
            fontWeight: 600,
            fontFamily: "'Space Grotesk', sans-serif",
          }}
        >
          Start free trial
        </a>
      </div>
    </nav>
  );
}

/* ─── REPORT PREVIEW CARD ───────────────────────────────────────── */
function ReportPreview() {
  const b1 = useRef<HTMLDivElement>(null);
  const b2 = useRef<HTMLDivElement>(null);
  const b3 = useRef<HTMLDivElement>(null);
  const b4 = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const bars = [
      { ref: b1, w: 88 },
      { ref: b2, w: 56 },
      { ref: b3, w: 30 },
      { ref: b4, w: 12 },
    ];
    const timers = bars.map(({ ref, w }, i) =>
      setTimeout(() => { if (ref.current) ref.current.style.width = `${w}%`; }, 600 + i * 150)
    );
    return () => timers.forEach(clearTimeout);
  }, []);

  return (
    <div style={{ width: "100%", maxWidth: 860, margin: "0 auto", background: "var(--navy-3)", border: "1px solid var(--border)", borderRadius: 16, overflow: "hidden", boxShadow: "0 40px 80px rgba(0,0,0,0.6)" }}>
      <div style={{ background: "var(--navy-2)", padding: "16px 24px", display: "flex", alignItems: "center", justifyContent: "space-between", borderBottom: "1px solid var(--border)" }}>
        <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
          <div style={{ width: 36, height: 36, borderRadius: "50%", background: "linear-gradient(135deg,var(--cyan),#5b8fff)", display: "flex", alignItems: "center", justifyContent: "center", fontFamily: "'Space Grotesk',sans-serif", fontSize: 12, fontWeight: 700, color: "var(--navy)" }}>AC</div>
          <div>
            <div style={{ fontFamily: "'Space Grotesk',sans-serif", fontSize: 14, fontWeight: 600, color: "var(--white)" }}>Apex Creative — Weekly Report</div>
            <div style={{ fontSize: 12, color: "var(--muted)" }}>Jun 2 – Jun 8, 2026 · Generated by Pulse</div>
          </div>
        </div>
        <div style={{ background: "rgba(0,229,204,0.1)", border: "1px solid rgba(0,229,204,0.25)", color: "var(--cyan)", fontSize: 11, fontWeight: 600, padding: "4px 10px", borderRadius: 100 }}>✦ AI-analysed</div>
      </div>
      <div style={{ display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: 1, background: "var(--border)", borderBottom: "1px solid var(--border)" }}>
        {[
          { label: "Ad Spend", value: "$12,480", delta: "+8.3%", up: true },
          { label: "Revenue", value: "$94,210", delta: "+22.1%", up: true },
          { label: "ROAS", value: "7.55×", delta: "+12.6%", up: true },
          { label: "Blended CAC", value: "$34.20", delta: "-18.4%", up: false },
        ].map(({ label, value, delta, up }) => (
          <div key={label} style={{ background: "var(--navy-3)", padding: "20px 24px" }}>
            <div style={{ fontSize: 11, fontWeight: 500, color: "var(--muted)", textTransform: "uppercase", letterSpacing: "0.5px", marginBottom: 6 }}>{label}</div>
            <div style={{ fontFamily: "'Space Grotesk',sans-serif", fontSize: 26, fontWeight: 700, color: "var(--white)", marginBottom: 4 }}>{value}</div>
            <div style={{ fontSize: 12, fontWeight: 600, color: up ? "#4ade80" : "#f87171" }}>{delta} vs last week</div>
          </div>
        ))}
      </div>
      <div style={{ padding: 24, display: "grid", gridTemplateColumns: "1fr 1fr", gap: 20 }}>
        <div style={{ background: "var(--navy-2)", borderRadius: 10, padding: 16, border: "1px solid var(--border)" }}>
          <div style={{ fontSize: 11, fontWeight: 600, color: "var(--muted)", textTransform: "uppercase", letterSpacing: "0.5px", marginBottom: 12 }}>Traffic Sources</div>
          {[
            { label: "Paid Search", val: "4,821", ref: b1 },
            { label: "Meta Ads", val: "3,102", ref: b2 },
            { label: "Organic", val: "1,643", ref: b3 },
            { label: "Direct", val: "891", ref: b4 },
          ].map(({ label, val, ref }) => (
            <div key={label} style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 8 }}>
              <div style={{ fontSize: 12, color: "var(--muted)", width: 80, textAlign: "right", flexShrink: 0 }}>{label}</div>
              <div style={{ flex: 1, height: 6, background: "rgba(255,255,255,0.06)", borderRadius: 3, overflow: "hidden" }}>
                <div ref={ref} style={{ height: "100%", width: "0%", borderRadius: 3, background: "var(--cyan)", transition: "width 1s ease" }} />
              </div>
              <div style={{ fontSize: 12, fontWeight: 600, color: "var(--white)", width: 44, flexShrink: 0 }}>{val}</div>
            </div>
          ))}
        </div>
        <div style={{ background: "var(--navy-2)", borderRadius: 10, padding: 16, border: "1px solid var(--border)" }}>
          <div style={{ fontSize: 11, fontWeight: 600, color: "var(--muted)", textTransform: "uppercase", letterSpacing: "0.5px", marginBottom: 12 }}>Top Campaigns</div>
          {[
            { name: "Summer Sale — Retargeting", roas: "11.2×", spend: "$3,210" },
            { name: "Prospecting — Lookalike 5%", roas: "6.8×", spend: "$2,890" },
            { name: "Google PMax — All Products", roas: "5.9×", spend: "$4,100" },
            { name: "Brand Search — Exact", roas: "18.4×", spend: "$840" },
          ].map(({ name, roas, spend }) => (
            <div key={name} style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 10 }}>
              <div style={{ fontSize: 12, color: "var(--muted)", flex: 1, paddingRight: 8, overflow: "hidden", whiteSpace: "nowrap", textOverflow: "ellipsis" }}>{name}</div>
              <div style={{ display: "flex", gap: 12, flexShrink: 0 }}>
                <span style={{ fontSize: 12, fontWeight: 600, color: "#4ade80" }}>{roas}</span>
                <span style={{ fontSize: 12, color: "var(--muted)" }}>{spend}</span>
              </div>
            </div>
          ))}
        </div>
        <div style={{ gridColumn: "1/-1", background: "rgba(0,229,204,0.04)", border: "1px solid rgba(0,229,204,0.15)", borderRadius: 10, padding: 16 }}>
          <div style={{ fontSize: 11, fontWeight: 600, color: "var(--cyan)", textTransform: "uppercase", letterSpacing: "0.5px", marginBottom: 8 }}>✦ AI Analysis — What To Do Next</div>
          <p style={{ fontSize: 13, color: "var(--muted)", lineHeight: 1.7 }}>
            <strong style={{ color: "var(--white)", fontWeight: 500 }}>Strong week — your Summer Sale retargeting is your best performer at 11.2× ROAS.</strong>{" "}
            Scale that campaign by 30–40% this week before the sale window closes. Your Prospecting lookalike dropped from 8.2× last week — check frequency; if it&apos;s above 3.5, rotate creative.{" "}
            <strong style={{ color: "var(--white)", fontWeight: 500 }}>Blended CAC falling 18% while revenue is up 22% is a signal your funnel is tightening.</strong>{" "}
            Hold current budget allocation and review again Thursday.
          </p>
        </div>
      </div>
    </div>
  );
}

/* ─── HERO ──────────────────────────────────────────────────────── */
function Hero() {
  return (
    <section style={{ minHeight: "100vh", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", padding: "120px 40px 80px", textAlign: "center", position: "relative", overflow: "hidden" }}>
      <div style={{ position: "absolute", top: -200, left: "50%", transform: "translateX(-50%)", width: 800, height: 800, background: "radial-gradient(circle,rgba(0,229,204,0.08) 0%,transparent 70%)", pointerEvents: "none" }} />
      <div style={{ display: "inline-flex", alignItems: "center", gap: 8, background: "rgba(0,229,204,0.1)", border: "1px solid rgba(0,229,204,0.2)", borderRadius: 100, padding: "6px 16px", fontSize: 12, fontWeight: 500, color: "var(--cyan)", letterSpacing: "0.5px", textTransform: "uppercase", marginBottom: 28 }}>
        <span style={{ width: 6, height: 6, background: "var(--cyan)", borderRadius: "50%", display: "inline-block", animation: "pulse-dot 2s infinite" }} />
        Now live — automated reporting for agencies &amp; brands
      </div>
      <h1 style={{ fontFamily: "'Space Grotesk',sans-serif", fontSize: "clamp(42px,6vw,72px)", fontWeight: 700, lineHeight: 1.05, letterSpacing: "-2px", marginBottom: 24, color: "var(--white)" }}>
        Your business.{" "}
        <em style={{ color: "var(--cyan)", fontStyle: "normal" }}>Unmistakably clear.</em>
        <br />
        Every Monday.
      </h1>
      <p style={{ fontSize: 18, color: "var(--muted)", maxWidth: 560, margin: "0 auto 40px", lineHeight: 1.7 }}>
        Connect your ad accounts, store, and analytics once. Pulse pulls your data, writes the analysis, and delivers a boardroom-ready report to your inbox before you&apos;ve had your coffee.
      </p>
      <div style={{ display: "flex", gap: 16, justifyContent: "center", flexWrap: "wrap", marginBottom: 32 }}>
        <a href="#pricing" style={{ background: "var(--cyan)", color: "var(--navy)", padding: "14px 28px", borderRadius: 10, fontSize: 15, fontWeight: 600, fontFamily: "'Space Grotesk',sans-serif" }}>
          Start your free 14-day trial →
        </a>
        <a href="#features" style={{ background: "transparent", color: "var(--white)", padding: "14px 28px", borderRadius: 10, fontSize: 15, fontWeight: 500, border: "1px solid var(--border)", cursor: "pointer" }}>
          See how it works
        </a>
      </div>
      <div style={{ display: "flex", gap: 32, justifyContent: "center", alignItems: "center", color: "var(--muted)", fontSize: 13, flexWrap: "wrap", marginBottom: 64 }}>
        {["No credit card required", "Live in 48 hours", "Cancel anytime"].map((t) => (
          <span key={t} style={{ display: "flex", alignItems: "center", gap: 8 }}>
            <span style={{ color: "var(--cyan)", fontWeight: 700 }}>✓</span>{t}
          </span>
        ))}
      </div>
      <ReportPreview />
    </section>
  );
}

/* ─── LOGOS ─────────────────────────────────────────────────────── */
function Logos() {
  const logos = ["Meta Ads", "Google Ads", "Shopify", "GA4", "Klaviyo", "TikTok", "HubSpot", "Stripe"];
  return (
    <div style={{ padding: 40, borderTop: "1px solid var(--border)", borderBottom: "1px solid var(--border)" }}>
      <p style={{ textAlign: "center", fontSize: 13, color: "var(--muted)", marginBottom: 24 }}>Connects to every platform your business runs on</p>
      <div style={{ display: "flex", justifyContent: "center", alignItems: "center", gap: 48, flexWrap: "wrap" }}>
        {logos.map((l) => (
          <span key={l} style={{ fontFamily: "'Space Grotesk',sans-serif", fontSize: 16, fontWeight: 700, color: "rgba(255,255,255,0.2)", letterSpacing: "-0.5px" }}>{l}</span>
        ))}
      </div>
    </div>
  );
}

/* ─── FEATURES ──────────────────────────────────────────────────── */
function Features() {
  const features = [
    { icon: "✦", title: "AI-written analysis, not just charts", desc: "Every report includes a plain-English section that tells you exactly what happened, why it happened, and what to do about it. Like a strategist on retainer — minus the retainer." },
    { icon: "⚡", title: "Zero manual work after setup", desc: "Connect your platforms once. Pulse runs every week on autopilot — pulling data, generating the report, and emailing it — with no dashboards to log into or spreadsheets to update." },
    { icon: "📬", title: "In your inbox every Monday", desc: "Reports arrive before 7AM on Monday morning. Boardroom-ready, brand-consistent, and ready to forward to clients or use in your own strategy calls." },
    { icon: "🔔", title: "Anomaly alerts mid-week", desc: "If your ROAS drops 30% on a Wednesday, you'll know by Wednesday afternoon — not when you pull the report on Sunday. Alerts land via email or Slack." },
    { icon: "🔗", title: "12+ data sources, one report", desc: "Google Ads, Meta, Shopify, GA4, Klaviyo, TikTok, HubSpot, and more. All merged into a single coherent view with no manual cross-referencing." },
    { icon: "🏷️", title: "White-label for agencies", desc: "Scale clients get fully custom-branded reports — your logo, your colors, your sending domain. Clients think it's your proprietary system. It is." },
  ];
  return (
    <section id="features" style={{ padding: "100px 40px" }}>
      <div style={{ maxWidth: 1080, margin: "0 auto" }}>
        <div style={{ fontSize: 12, fontWeight: 600, color: "var(--cyan)", textTransform: "uppercase", letterSpacing: "1px", marginBottom: 16 }}>Features</div>
        <h2 style={{ fontFamily: "'Space Grotesk',sans-serif", fontSize: "clamp(32px,4vw,48px)", fontWeight: 700, letterSpacing: "-1px", lineHeight: 1.1, marginBottom: 20 }}>Everything you need.<br />Nothing you don&apos;t.</h2>
        <p style={{ fontSize: 17, color: "var(--muted)", maxWidth: 560, lineHeight: 1.7 }}>Built for marketing agencies and e-commerce brands who are done spending their Sunday nights on spreadsheets.</p>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: 1, background: "var(--border)", border: "1px solid var(--border)", borderRadius: 16, overflow: "hidden", marginTop: 60 }}>
          {features.map(({ icon, title, desc }) => (
            <div key={title} style={{ background: "var(--navy)", padding: 32, transition: "background .2s" }}
              onMouseEnter={(e) => ((e.currentTarget as HTMLDivElement).style.background = "var(--navy-3)")}
              onMouseLeave={(e) => ((e.currentTarget as HTMLDivElement).style.background = "var(--navy)")}
            >
              <div style={{ width: 44, height: 44, background: "rgba(0,229,204,0.1)", borderRadius: 10, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 20, marginBottom: 20 }}>{icon}</div>
              <div style={{ fontFamily: "'Space Grotesk',sans-serif", fontSize: 17, fontWeight: 600, marginBottom: 10, color: "var(--white)" }}>{title}</div>
              <div style={{ fontSize: 14, color: "var(--muted)", lineHeight: 1.7 }}>{desc}</div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

/* ─── INTEGRATIONS ──────────────────────────────────────────────── */
function Integrations() {
  const sources = [
    { icon: "📊", name: "Google Analytics", tag: "GA4" },
    { icon: "🎯", name: "Google Ads", tag: "Search & Display" },
    { icon: "📘", name: "Meta Ads", tag: "FB + Instagram" },
    { icon: "🛍️", name: "Shopify", tag: "E-commerce" },
    { icon: "📧", name: "Klaviyo", tag: "Email Marketing" },
    { icon: "🎵", name: "TikTok Ads", tag: "Short-form Video" },
    { icon: "🔶", name: "HubSpot", tag: "CRM" },
    { icon: "💳", name: "Stripe", tag: "Revenue" },
    { icon: "🎬", name: "YouTube", tag: "Content Analytics" },
    { icon: "🔵", name: "LinkedIn Ads", tag: "B2B Ads" },
    { icon: "📌", name: "Pinterest Ads", tag: "Visual Ads" },
    { icon: "⚙️", name: "GoHighLevel", tag: "Agency CRM" },
  ];
  return (
    <section id="integrations" style={{ padding: "100px 40px", background: "var(--navy-2)", borderTop: "1px solid var(--border)", borderBottom: "1px solid var(--border)" }}>
      <div style={{ maxWidth: 1080, margin: "0 auto" }}>
        <div style={{ fontSize: 12, fontWeight: 600, color: "var(--cyan)", textTransform: "uppercase", letterSpacing: "1px", marginBottom: 16 }}>Integrations</div>
        <h2 style={{ fontFamily: "'Space Grotesk',sans-serif", fontSize: "clamp(32px,4vw,48px)", fontWeight: 700, letterSpacing: "-1px", lineHeight: 1.1, marginBottom: 20 }}>Every platform.<br />One report.</h2>
        <p style={{ fontSize: 17, color: "var(--muted)", maxWidth: 560, lineHeight: 1.7 }}>Pulse connects to the tools your business already runs on. No data warehouse needed. No engineers. Just connect and go.</p>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(130px,1fr))", gap: 12, marginTop: 48 }}>
          {sources.map(({ icon, name, tag }) => (
            <div key={name} style={{ background: "var(--navy-3)", border: "1px solid var(--border)", borderRadius: 10, padding: 16, display: "flex", flexDirection: "column", alignItems: "center", gap: 8, transition: "border-color .2s" }}
              onMouseEnter={(e) => ((e.currentTarget as HTMLDivElement).style.borderColor = "rgba(0,229,204,0.3)")}
              onMouseLeave={(e) => ((e.currentTarget as HTMLDivElement).style.borderColor = "var(--border)")}
            >
              <div style={{ fontSize: 22 }}>{icon}</div>
              <div style={{ fontSize: 12, fontWeight: 600, color: "var(--white)", textAlign: "center" }}>{name}</div>
              <div style={{ fontSize: 10, color: "var(--muted)", textTransform: "uppercase", letterSpacing: "0.3px", textAlign: "center" }}>{tag}</div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

/* ─── HOW IT WORKS ──────────────────────────────────────────────── */
function HowItWorks() {
  const steps = [
    { n: "1", title: "Connect your platforms", desc: "Link your Google, Meta, Shopify, and other accounts in minutes. OAuth-secured — we never store passwords." },
    { n: "2", title: "Set your report preferences", desc: "Choose your delivery day, your KPIs, and your tone. Pulse learns what matters to your business." },
    { n: "3", title: "Receive your first report", desc: "Within 48 hours, your first AI-written report lands in your inbox. Boardroom-ready from day one." },
    { n: "4", title: "Never think about it again", desc: "Pulse runs every week on autopilot. You just open your inbox on Monday and make decisions." },
  ];
  return (
    <section style={{ padding: "100px 40px" }}>
      <div style={{ maxWidth: 1080, margin: "0 auto" }}>
        <div style={{ fontSize: 12, fontWeight: 600, color: "var(--cyan)", textTransform: "uppercase", letterSpacing: "1px", marginBottom: 16 }}>How it works</div>
        <h2 style={{ fontFamily: "'Space Grotesk',sans-serif", fontSize: "clamp(32px,4vw,48px)", fontWeight: 700, letterSpacing: "-1px", lineHeight: 1.1, marginBottom: 60 }}>Live in 48 hours.<br />Automated forever.</h2>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: 40 }}>
          {steps.map(({ n, title, desc }) => (
            <div key={n}>
              <div style={{ width: 48, height: 48, borderRadius: "50%", background: "rgba(0,229,204,0.1)", border: "1px solid rgba(0,229,204,0.2)", display: "flex", alignItems: "center", justifyContent: "center", fontFamily: "'Space Grotesk',sans-serif", fontSize: 18, fontWeight: 700, color: "var(--cyan)", marginBottom: 20 }}>{n}</div>
              <div style={{ fontFamily: "'Space Grotesk',sans-serif", fontSize: 17, fontWeight: 600, marginBottom: 12, color: "var(--white)" }}>{title}</div>
              <div style={{ fontSize: 14, color: "var(--muted)", lineHeight: 1.7 }}>{desc}</div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

/* ─── PRICING ───────────────────────────────────────────────────── */
// Pricing buttons POST to /api/stripe/checkout → get back a Stripe URL → redirect
// The webhook at /api/webhooks/stripe then provisions the Clerk user + sends welcome email
function Pricing() {
  const [loading, setLoading] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  async function startCheckout(plan: string) {
    setLoading(plan);
    setError(null);
    try {
      const res = await fetch("/api/stripe/checkout", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ plan }),
      });
      const data = await res.json();
      if (data.url) {
        window.location.href = data.url;
      } else {
        setError("Something went wrong. Please try again.");
        setLoading(null);
      }
    } catch {
      setError("Something went wrong. Please try again.");
      setLoading(null);
    }
  }

  const plans = [
    {
      key: "starter",
      name: "Starter",
      price: "$297",
      desc: "For solo operators, local businesses, and early-stage creators who need clarity without complexity.",
      features: ["Weekly automated email report", "Up to 3 data sources connected", "Live dashboard (always-on)", "Monthly PDF summary", "Email support"],
      cta: "Start free trial →",
      featured: false,
    },
    {
      key: "growth",
      name: "Growth",
      price: "$597",
      desc: "For agencies and e-commerce brands that manage multiple platforms and need real AI analysis.",
      features: ["Everything in Starter", "Up to 8 data sources", "AI-written 'what to do next' analysis", "Anomaly alerts via Slack or email", "Monthly 30-min strategy call"],
      cta: "Start free trial →",
      featured: true,
    },
    {
      key: "scale",
      name: "Scale",
      price: "$1,197",
      desc: "For multi-location brands, funded startups, and agencies managing 15+ clients at once.",
      features: ["Everything in Growth", "Unlimited data sources", "Custom branded report design", "Multi-location / multi-brand", "White-label reseller option"],
      cta: "Start free trial →",
      featured: false,
    },
  ];

  return (
    <section id="pricing" style={{ padding: "100px 40px", background: "var(--navy-2)", borderTop: "1px solid var(--border)", borderBottom: "1px solid var(--border)" }}>
      <div style={{ maxWidth: 1080, margin: "0 auto" }}>
        <div style={{ fontSize: 12, fontWeight: 600, color: "var(--cyan)", textTransform: "uppercase", letterSpacing: "1px", marginBottom: 16 }}>Pricing</div>
        <h2 style={{ fontFamily: "'Space Grotesk',sans-serif", fontSize: "clamp(32px,4vw,48px)", fontWeight: 700, letterSpacing: "-1px", lineHeight: 1.1, marginBottom: 20 }}>One price.<br />Zero surprises.</h2>
        <p style={{ fontSize: 17, color: "var(--muted)", maxWidth: 560, lineHeight: 1.7, marginBottom: 56 }}>
          Every plan includes a 14-day free trial. No credit card until you&apos;re sure it&apos;s the best thing you&apos;ve ever automated.
        </p>

        {error && (
          <div style={{ background: "rgba(248,113,113,0.1)", border: "1px solid rgba(248,113,113,0.3)", borderRadius: 8, padding: "12px 16px", color: "#f87171", fontSize: 14, marginBottom: 24 }}>
            {error}
          </div>
        )}

        <div style={{ display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: 20 }}>
          {plans.map(({ key, name, price, desc, features, cta, featured }) => (
            <div key={key} style={{ background: featured ? "rgba(0,229,204,0.04)" : "var(--navy-2)", border: featured ? "1px solid var(--cyan)" : "1px solid var(--border)", borderRadius: 16, padding: 32, position: "relative" }}>
              {featured && (
                <div style={{ position: "absolute", top: -14, left: "50%", transform: "translateX(-50%)", background: "var(--cyan)", color: "var(--navy)", fontSize: 11, fontWeight: 700, padding: "4px 16px", borderRadius: 100, whiteSpace: "nowrap", fontFamily: "'Space Grotesk',sans-serif", textTransform: "uppercase", letterSpacing: "0.5px" }}>
                  Most popular
                </div>
              )}
              <div style={{ fontFamily: "'Space Grotesk',sans-serif", fontSize: 14, fontWeight: 600, color: "var(--muted)", textTransform: "uppercase", letterSpacing: "1px", marginBottom: 16 }}>{name}</div>
              <div style={{ display: "flex", alignItems: "baseline", gap: 4, marginBottom: 8 }}>
                <span style={{ fontFamily: "'Space Grotesk',sans-serif", fontSize: 48, fontWeight: 700, color: "var(--white)", letterSpacing: "-2px" }}>{price}</span>
                <span style={{ color: "var(--muted)", fontSize: 15 }}>/month</span>
              </div>
              <p style={{ fontSize: 14, color: "var(--muted)", lineHeight: 1.6, marginBottom: 24 }}>{desc}</p>
              <div style={{ height: 1, background: "var(--border)", marginBottom: 24 }} />
              {features.map((f) => (
                <div key={f} style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 12, fontSize: 14, color: "var(--white)" }}>
                  <span style={{ color: "var(--cyan)", fontWeight: 700 }}>✓</span>{f}
                </div>
              ))}
              <button
                onClick={() => startCheckout(key)}
                disabled={loading !== null}
                style={{
                  display: "block",
                  width: "100%",
                  textAlign: "center",
                  marginTop: 32,
                  padding: "12px 24px",
                  borderRadius: 10,
                  fontFamily: "'Space Grotesk',sans-serif",
                  fontSize: 14,
                  fontWeight: 600,
                  cursor: loading !== null ? "wait" : "pointer",
                  opacity: loading !== null && loading !== key ? 0.6 : 1,
                  transition: "opacity .2s",
                  border: "none",
                  ...(featured
                    ? { background: "var(--cyan)", color: "var(--navy)" }
                    : { background: "transparent", color: "var(--white)", border: "1px solid var(--border)" }),
                }}
              >
                {loading === key ? "Redirecting to checkout…" : cta}
              </button>
            </div>
          ))}
        </div>

        <p style={{ textAlign: "center", fontSize: 13, color: "var(--muted)", marginTop: 32 }}>
          After checkout, you&apos;ll receive a sign-in link by email. No account needed upfront.
        </p>
      </div>
    </section>
  );
}

/* ─── TESTIMONIALS ──────────────────────────────────────────────── */
function Testimonials() {
  const testimonials = [
    { text: "I used to spend 4 hours every Sunday night pulling numbers for Monday client calls. Now I wake up and it's already in my inbox. Pulse paid for itself in the first week.", name: "Jason R.", role: "Founder, paid media agency · 23 clients", initials: "JR", color: "rgba(0,229,204,0.2)", textColor: "var(--cyan)" },
    { text: "The AI commentary section is what sold me. It doesn't just show me numbers — it tells me what they mean and what to change. Like having a strategist on retainer for a fraction of the cost.", name: "Sarah M.", role: "DTC brand founder · $2.3M annual revenue", initials: "SM", color: "rgba(91,143,255,0.2)", textColor: "#5b8fff" },
    { text: "We white-labeled Pulse for all 31 of our agency clients. They think it's our proprietary reporting system. Retention went up 40% in three months. Best investment we've made.", name: "Daniel P.", role: "CEO, full-service digital agency", initials: "DP", color: "rgba(255,144,0,0.2)", textColor: "#ff9000" },
  ];
  return (
    <section style={{ padding: "100px 40px" }}>
      <div style={{ maxWidth: 1080, margin: "0 auto" }}>
        <div style={{ fontSize: 12, fontWeight: 600, color: "var(--cyan)", textTransform: "uppercase", letterSpacing: "1px", marginBottom: 16 }}>What clients say</div>
        <h2 style={{ fontFamily: "'Space Grotesk',sans-serif", fontSize: "clamp(32px,4vw,48px)", fontWeight: 700, letterSpacing: "-1px", lineHeight: 1.1, marginBottom: 56 }}>The best Monday morning<br />they&apos;ve ever had.</h2>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: 20 }}>
          {testimonials.map(({ text, name, role, initials, color, textColor }) => (
            <div key={name} style={{ background: "var(--navy-2)", border: "1px solid var(--border)", borderRadius: 16, padding: 32 }}>
              <div style={{ color: "#f59e0b", fontSize: 16, marginBottom: 20, letterSpacing: 2 }}>★★★★★</div>
              <p style={{ fontSize: 14, color: "var(--muted)", lineHeight: 1.7, marginBottom: 24 }}>&quot;{text}&quot;</p>
              <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
                <div style={{ width: 40, height: 40, borderRadius: "50%", background: color, color: textColor, display: "flex", alignItems: "center", justifyContent: "center", fontFamily: "'Space Grotesk',sans-serif", fontSize: 13, fontWeight: 700, flexShrink: 0 }}>{initials}</div>
                <div>
                  <div style={{ fontFamily: "'Space Grotesk',sans-serif", fontSize: 14, fontWeight: 600, color: "var(--white)" }}>{name}</div>
                  <div style={{ fontSize: 12, color: "var(--muted)" }}>{role}</div>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

/* ─── CTA ───────────────────────────────────────────────────────── */
function CTA() {
  return (
    <section style={{ padding: "100px 40px", background: "radial-gradient(ellipse at center,rgba(0,229,204,0.06) 0%,transparent 70%), var(--navy-2)", borderTop: "1px solid var(--border)", textAlign: "center" }}>
      <div style={{ maxWidth: 640, margin: "0 auto" }}>
        <h2 style={{ fontFamily: "'Space Grotesk',sans-serif", fontSize: "clamp(36px,5vw,56px)", fontWeight: 700, letterSpacing: "-2px", lineHeight: 1.1, marginBottom: 20 }}>Stop making reports.<br />Start making decisions.</h2>
        <p style={{ fontSize: 18, color: "var(--muted)", marginBottom: 40, lineHeight: 1.7 }}>Join hundreds of agencies and brands who automated their Monday mornings with Pulse.</p>
        <a href="#pricing" style={{ display: "inline-block", background: "var(--cyan)", color: "var(--navy)", padding: "16px 36px", borderRadius: 10, fontSize: 16, fontWeight: 600, fontFamily: "'Space Grotesk',sans-serif", marginBottom: 16 }}>
          Start your free 14-day trial →
        </a>
        <p style={{ fontSize: 13, color: "var(--muted)" }}>No credit card required. Cancel anytime. Live in 48 hours.</p>
      </div>
    </section>
  );
}

/* ─── FOOTER ────────────────────────────────────────────────────── */
function Footer() {
  return (
    <footer style={{ padding: "40px", borderTop: "1px solid var(--border)", display: "flex", alignItems: "center", justifyContent: "space-between", flexWrap: "wrap", gap: 16 }}>
      <span style={{ fontFamily: "'Space Grotesk',sans-serif", fontSize: 20, fontWeight: 700, color: "var(--white)" }}>Pulse<span style={{ color: "var(--cyan)" }}>.</span></span>
      <div style={{ display: "flex", gap: 32 }}>
        {["Privacy", "Terms", "Contact"].map((l) => (
          <a key={l} href="#" style={{ fontSize: 14, color: "var(--muted)" }}>{l}</a>
        ))}
      </div>
      <p style={{ fontSize: 13, color: "var(--muted)" }}>© 2026 Pulse. Automated business intelligence.</p>
    </footer>
  );
}

/* ─── PAGE ──────────────────────────────────────────────────────── */
export default function HomePage() {
  return (
    <>
      <style>{`
        @keyframes pulse-dot { 0%, 100% { opacity: 1; } 50% { opacity: 0.3; } }
      `}</style>
      <Nav />
      <main>
        <Hero />
        <Logos />
        <Features />
        <Integrations />
        <HowItWorks />
        <Pricing />
        <Testimonials />
        <CTA />
      </main>
      <Footer />
    </>
  );
}
