import { Resend } from "resend";
import type { ConnectorData } from "@/lib/connectors";

function getResend() {
  return new Resend(process.env.RESEND_API_KEY!);
}

function fmt(n: number, prefix = "") {
  if (n >= 1_000_000) return `${prefix}${(n / 1_000_000).toFixed(2)}M`;
  if (n >= 1_000) return `${prefix}${(n / 1_000).toFixed(1)}K`;
  return `${prefix}${n.toFixed(2)}`;
}

function buildEmailHtml(
  companyName: string,
  data: ConnectorData,
  commentary: string,
  weekLabel: string
): string {
  const metrics = [
    { label: "Ad Spend", value: fmt(data.ad_spend ?? 0, "$") },
    { label: "Revenue", value: fmt(data.revenue ?? 0, "$") },
    { label: "Blended ROAS", value: `${(data.blended_roas ?? 0).toFixed(2)}×` },
    { label: "Orders", value: fmt(data.shopify_orders ?? 0) },
  ];

  return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Pulse Weekly Report</title></head>
<body style="margin:0;padding:0;background:#0A0F1E;font-family:Inter,sans-serif;color:#F0F4FF">
  <div style="max-width:640px;margin:0 auto;padding:40px 20px">
    <!-- Header -->
    <div style="margin-bottom:32px">
      <span style="font-family:'Space Grotesk',sans-serif;font-size:22px;font-weight:700;color:#F0F4FF">Pulse<span style="color:#00E5CC">.</span></span>
    </div>
    <h1 style="font-family:'Space Grotesk',sans-serif;font-size:24px;font-weight:700;margin:0 0 8px;letter-spacing:-0.5px">${companyName} — Weekly Report</h1>
    <p style="font-size:14px;color:#8892A4;margin:0 0 32px">${weekLabel} · Generated by Pulse</p>
    
    <!-- Metrics -->
    <div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-bottom:32px">
      ${metrics
        .map(
          ({ label, value }) => `
      <div style="background:#111827;border:1px solid rgba(255,255,255,0.08);border-radius:10px;padding:20px">
        <div style="font-size:11px;font-weight:600;color:#8892A4;text-transform:uppercase;letter-spacing:0.5px;margin-bottom:8px">${label}</div>
        <div style="font-family:'Space Grotesk',sans-serif;font-size:28px;font-weight:700;letter-spacing:-1px">${value}</div>
      </div>`
        )
        .join("")}
    </div>
    
    <!-- AI Commentary -->
    <div style="background:rgba(0,229,204,0.04);border:1px solid rgba(0,229,204,0.15);border-radius:10px;padding:20px;margin-bottom:32px">
      <div style="font-size:11px;font-weight:600;color:#00E5CC;text-transform:uppercase;letter-spacing:0.5px;margin-bottom:12px">✦ AI Analysis — What To Do Next</div>
      <p style="font-size:14px;color:#8892A4;line-height:1.7;margin:0">${commentary}</p>
    </div>
    
    <!-- CTA -->
    <div style="text-align:center;margin-bottom:40px">
      <a href="${process.env.NEXT_PUBLIC_APP_URL}/dashboard/reports" style="display:inline-block;background:#00E5CC;color:#0A0F1E;padding:12px 24px;border-radius:8px;font-family:'Space Grotesk',sans-serif;font-size:14px;font-weight:600;text-decoration:none">View full report →</a>
    </div>
    
    <!-- Footer -->
    <div style="border-top:1px solid rgba(255,255,255,0.08);padding-top:24px;font-size:12px;color:#8892A4;text-align:center">
      <p style="margin:0 0 8px">You're receiving this because you connected your platforms to Pulse.</p>
      <p style="margin:0"><a href="${process.env.NEXT_PUBLIC_APP_URL}/dashboard/settings" style="color:#00E5CC">Manage preferences</a> · <a href="${process.env.NEXT_PUBLIC_APP_URL}" style="color:#8892A4">Pulse</a></p>
    </div>
  </div>
</body></html>`;
}

export async function sendReport({
  user,
  data,
  commentary,
}: {
  user: { email: string; company_name?: string | null; full_name?: string | null };
  data: ConnectorData;
  commentary: string;
}) {
  const companyName = user.company_name ?? user.full_name ?? "Your Business";
  const now = new Date();
  const weekStart = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
  const weekLabel = `${weekStart.toLocaleDateString("en-US", { month: "short", day: "numeric" })} – ${now.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}`;

  const html = buildEmailHtml(companyName, data, commentary, weekLabel);

  await getResend().emails.send({
    from: process.env.RESEND_FROM_EMAIL!,
    to: user.email,
    subject: `${companyName} — Weekly Performance Report (${weekLabel})`,
    html,
  });
}
